### PR TITLE
Only depend on fail with ancient compilers

### PR DESCRIPTION
**Pull request by clinty**

### CODE REVIEW

**Comment by byorgey** [comment]
Thanks!  Makes sense.  And just to clarify, does this correct a problem you were having?  Or is it more just a sort of "we should do things the right way" sort of change?

**Comment by clinty** [comment]
It just saves Debian the labor of patching out the use of fail (which is an empty package and thus cannot be built): not a big time sink, but an unrewarding one.

**Comment by byorgey** [comment]
Ah, OK, so it does correct a problem.  Thanks!

**Comment by byorgey** [comment]
Released to Hackage as 0.5.1.1.

**Pull request merged**
